jobs:
  calculate-coverage:
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      uses: actions/checkout@master
    - continue-on-error: true
      name: Set up JDK 8
      uses: actions/setup-java@v2
      with:
        cache: maven
        distribution: adopt
        java-version: '8'
    - continue-on-error: true
      name: Generate coverage report
      run: mvn -B test -T 2C --file pom.xml
    - continue-on-error: true
      name: Upload to Codecov
      uses: codecov/codecov-action@v3
      with:
        fail_ci_if_error: true
        verbose: true
name: Coverage
on:
  repository_dispatch:
    types: trigger-ga___coverage.yml
