jobs:
  check-license:
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      uses: actions/checkout@v3
    - continue-on-error: true
      name: Check License Header
      uses: apache/skywalking-eyes@v0.2.0
      with:
        config: .licenserc.yaml
        log: info
name: License checker
on:
  repository_dispatch:
    types: trigger-ga___license-checker.yaml
